[project]
name = "password-strength"
version = "0.1.0"
description = "A simple password strength checker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "requests",
    "re",
    "string",
    "math",
    "random"
]
