[tool.poetry]
name = "password-strength"
version = "0.1.0"
description = "A simple password strength checker"
authors = ["Subham"]

package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
streamlit = "*"
requests = "*"
